### ISSUE TITLE
Unable to install with composer due to stability level

### ISSUE THREAD

**Issue by eborned** [Filsh/yii2-oauth2-server#10]
My fresh installation of yii2-advanced does not accept the current stability level of this package:

    composer require --prefer-dist filsh/yii2-oauth2-server "*"

does not work. Instead I used:

    composer require --prefer-dist filsh/yii2-oauth2-server "@dev"

**Comment by rollwhistler** [comment]
and with that it worked whitout doing anything else? i got it runnig, but i got the error i posted some minutes ago :(
