### ISSUE TITLE
Declaration of m140501_075311_add_oauth2_server::primaryKey($columns) should be compatible with yii\db\Migration::primaryKey($length = NULL)

### ISSUE THREAD

**Issue by Faryshta** [Filsh/yii2-oauth2-server#109]
The command

``` sh
./yii migrate/up --migrationPath=@vendor/filsh/yii2-oauth2-server/migrations
```

Throws with ErrorException with the message "Declaration of m140501_075311_add_oauth2_server::primaryKey($columns) should be compatible with yii\db\Migration::primaryKey($length = NULL)" when using yii 2.0.10-dev

To solve this I propose to create a new method instead of using the existing one.

``` php
public function primaryKeyColumns(array $columns)
{

}
```

and use that instead.

**Comment by brutto** [comment]
@Faryshta Hi, if you empty this method -- you have no any pimary keys on tables and need to add them manually. Check this [PR](https://github.com/Filsh/yii2-oauth2-server/pull/110) with fix your issue.

**Comment by brutto** [comment]
found just fixed @master branch

**Comment by Faryshta** [comment]
thanks @brutto sadly the jwt support in the master branch seem to have derrailed the entire repo. It doesn't run at master anymore, i had to fork this and probably will have to fully fork it soon if things doesn't improve

**Comment by windhoney** [comment]
public function primaryKey($columns=null) {
        return 'PRIMARY KEY (' . $this->db->getQueryBuilder()->buildColumns($columns) . ')';
    }
_**Parameters need default values**_   
   ### **primaryKey($columns=null)**
