### ISSUE TITLE
storage of type "user_credentials" must implement interface "OAuth2\\Storage\\UserCredentialsInterface\"

### ISSUE THREAD

**Issue by rollwhistler** [Filsh/yii2-oauth2-server#11]
Hi, 

i'm getting this error, the stack shows that it blows up on Module.php file line 34:

$server = new \OAuth2\Server($storages, $this->options);

$storages is filled with objects created using Yii:createObject() i don't know if this is the reason why bshaffer module is complaining...

any hints? maybe i should try to use an older version of bshaffer module?

**Comment by rollwhistler** [comment]
Sorry i missed the change on the user module to add the correct implementation interface... my bad.

**Comment by mtangoo** [comment]
#43
