### ISSUE TITLE
I don't know why is it，how to solve the question?

### ISSUE THREAD

**Issue by yuxiuhong** [Filsh/yii2-oauth2-server#115]
{
name: "Bad Request"
message: "Grant type "token" not supported"
code: 0
status: 400
type: "filsh\yii2\oauth2server\exceptions\HttpException"
}

I need use 'token' .   "Grant type "token" not supported"!  why???

<form id="form1" method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        username:<input type="text" name="username"/><br/>
        password:<input type="password" name="password"/><br/>
        <input type="hidden" name="client_id" value="testclient"/>
        <input type="hidden" name="client_secret" value="testpass"/>
        <input type="hidden" name="grant_type" value="password"/>
        <input type="submit" id="btn" value="test"/>
    </form>
This can successfully return result,but next can't.

<form method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        client_id:<input type="text" name="client_id"/><br/>
        <input type="hidden" name="response_type" value="code"/>
        <input type="submit" id="btn" value="test"/>
    </form>

**Comment by mtangoo** [comment]
show sample request

**Comment by yuxiuhong** [comment]
<form id="form1" method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        username:<input type="text" name="username"/><br/>
        password:<input type="password" name="password"/><br/>
        <input type="hidden" name="client_id" value="testclient"/>
        <input type="hidden" name="client_secret" value="testpass"/>
        <input type="hidden" name="grant_type" value="password"/>
        <input type="submit" id="btn" value="test"/>
    </form>
This can successfully return result,but next can't.

<form method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        client_id:<input type="text" name="client_id"/><br/>
        <input type="hidden" name="response_type" value="code"/>
        <input type="submit" id="btn" value="test"/>
    </form>

**Comment by mtangoo** [comment]
Please post something that is testable. Your details are not enough.
Post your full request with sensitive information replaced by dummy

**Comment by yuxiuhong** [comment]
`<form id="form1" method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        username:<input type="text" name="username"/><br/>
        password:<input type="password" name="password"/><br/>
        <input type="hidden" name="client_id" value="testclient"/>
        <input type="hidden" name="client_secret" value="testpass"/>
        <input type="hidden" name="grant_type" value="password"/>
        <input type="submit" id="btn" value="test"/>
    </form>
This can successfully return result,but next can't.

<form method="post" action="http://localhost/advanced_yii/backend/web/index.php/oauth2/token">
        client_id:<input type="text" name="client_id"/><br/>
        <input type="hidden" name="response_type" value="code"/>
        <input type="submit" id="btn" value="test"/>
    </form>`
