### ISSUE TITLE
RESTful Apis Get accessToken from user object

### ISSUE THREAD

**Issue by veronicavg** [Filsh/yii2-oauth2-server#124]
When I perform the social login from my app, in the rest controller I create the user instance (if not exist), then i have to return the access token. In this case i don't have the password, i must create the token from the user object.
How can i do that?

**Comment by veronicavg** [comment]
I find this
 ```
public function createAccessToken($clientId, $userId, $scope = null, $includeRefreshToken = true)
    {
        $accessToken = $this->getAccessTokenResponseType();
        return $accessToken->createAccessToken($clientId, $userId, $scope, $includeRefreshToken);
    }
```
in Server.php.
But how to use it?

**Comment by mtangoo** [comment]
have you read instructions in readme? If yes what's your problem?

**Comment by veronicavg** [comment]
Read and read again.
I solved my problem in that way:
