### ISSUE TITLE
Migrations unsuccessful with Yii 2.0.11.2

### ISSUE THREAD

**Issue by snowwolf007cn** [filsh/yii2-oauth2-server#126]
$ ./yii migrate --migrationPath=@vendor/filsh/yii2-oauth2-server/migrations
Yii Migration Tool (based on Yii v2.0.11.2)

Total 1 new migration to be applied:
	m140501_075311_add_oauth2_server

Apply the above migration? (yes|no) [no]:yes
*** applying m140501_075311_add_oauth2_server
PHP Warning 'yii\base\ErrorException' with message 'Declaration of m140501_075311_add_oauth2_server::primaryKey($columns) should be compatible with yii\db\Migration::primaryKey($length = NULL)'

in /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/filsh/yii2-oauth2-server/migrations/m140501_075311_add_oauth2_server.php:5

Stack trace:
#0 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(653): yii\console\controllers\MigrateController->createMigration()
#1 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp()
#2 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\console\controllers\BaseMigrateController->actionUp()
#3 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#4 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams()
#5 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction()
#6 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction()
#7 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#8 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction()
#9 /Users/zhangzhi/workspace/bdqn/Breakfast/source/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest()
#10 /Users/zhangzhi/workspace/bdqn/Breakfast/source/yii(27): yii\base\Application->run()

**Comment by kiwinewt** [comment]
Change line 12 to :     public function customPrimaryKey($columns) { and everywhere it calls '$this->primaryKey(' to '$this->customPrimaryKey('

**Comment by varp** [comment]
@kiwinewt @snowwolf007cn  Already resolved in the master branch!
