### ISSUE TITLE
Methods PUT and DELETE no longer working when activating the behaviour

### ISSUE THREAD

**Issue by rollwhistler** [filsh/yii2-oauth2-server#13]
Hi there,

if i add the behaviour in a controller to activate the OAuth validation, the getBodyParams() function no longer works and returns an empty body... so i cannot use any methods other than GET and POST...

Why is that? is there a workarround?

**Comment by ventayol** [comment]
@Filsh I've found a really strange thing.
Look like this method from `CompositeAuth` class does something with the request:

            $oauthRequest = Yii::$app->getModule('oauth2')->getRequest();

if you call `Yii::$app->getRequest()->getBodyParams();` before calling the previous method everything works fine, but you don't do this, the function does something and the request body is lost.

**Comment by varp** [comment]
The latest release has support for Yii >= v2.0.13
