### ISSUE TITLE
Is this project still live?

### ISSUE THREAD

**Issue by deadmantfa** [filsh/yii2-oauth2-server#133]
Hi @Filsh ,
Just wanted to know if this project is still live and updates would be coming in.

I am trying to use it for a new project where I want to use openid with oauth.

Does your project support that?

Regards,
Wenceslaus Dsilva

**Comment by filipe1309** [comment]
Hey @Filsh,
I have the same doubt, and in my case, i want to use this extension in a project that i need to create a server for OpenID Connect.

**Comment by yogeshs1989** [comment]
It seems this project is not active, because no update in code from last 1 year.

**Comment by varp** [comment]
@deadmantfa @filipe1309 @yogeshs1989 The project is alive again.
