### ISSUE TITLE
oauth2/token 使用最新的yii2版本，访问报错

### ISSUE THREAD

**Issue by asialong** [filsh/yii2-oauth2-server#137]
错误信息：Class user_credentials does not exist
`{
    "name": "Exception",
    "message": "Class user_credentials does not exist",
    "code": -1,
    "type": "ReflectionException",
    "file": "/www/wwwroot/local.user.com/vendor/yiisoft/yii2/di/Container.php",
    "line": 428,
    "stack-trace": [
        "#0 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/di/Container.php(428): ReflectionClass->__construct('user_credential...')",
        "#1 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/di/Container.php(364): yii\\di\\Container->getDependencies('user_credential...')",
        "#2 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/di/Container.php(156): yii\\di\\Container->build('user_credential...', Array, Array)",
        "#3 /www/wwwroot/local.user.com/vendor/filsh/yii2-oauth2-server/Module.php(100): yii\\di\\Container->get('user_credential...')",
        "#4 /www/wwwroot/local.user.com/vendor/filsh/yii2-oauth2-server/controllers/DefaultController.php(25): filsh\\yii2\\oauth2server\\Module->getServer()",
        "#5 [internal function]: filsh\\yii2\\oauth2server\\controllers\\DefaultController->actionToken()",
        "#6 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
        "#7 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)",
        "#8 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/base/Module.php(528): yii\\base\\Controller->runAction('token', Array)",
        "#9 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module->runAction('oauth2/default/...', Array)",
        "#10 /www/wwwroot/local.user.com/vendor/yiisoft/yii2/base/Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))",
        "#11 /www/wwwroot/local.user.com/api/index.php(17): yii\\base\\Application->run()",
        "#12 {main}"
    ]
}`

**Comment by varp** [comment]
Fixed in v2.1.0
