### ISSUE TITLE
How to install and run

### ISSUE THREAD

**Issue by mangesh0550** [filsh/yii2-oauth2-server#139]
please  help

**Comment by mangesh0550** [comment]
latest

**Comment by mangesh0550** [comment]
current version

**Comment by IlmLV** [comment]
this repo currently is not compatible with latest yii2 version, I was facing same problem
suggesting you to test some forks with recently added commits
currently I ended up using https://github.com/hosannahighertech/yii2-oauth2-server

**Comment by mangesh0550** [comment]
so can i update "hosannahighertech/yii2-oauth2-server": "1.0.*" this in my composer

**Comment by mangesh0550** [comment]
hi sir iam facing     "message": "SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'expires' at row 1", this error

**Comment by IlmLV** [comment]
that's odd, I was able to switch from Filsh to hosannahighertech without any issues
check if this problem is actually related with switching to this fork

also you can report this issue to hosannahighertech repo
