### ISSUE TITLE
Add 'auth_code_lifetime' support to config

### ISSUE THREAD

**Issue by NickvdMeij** [filsh/yii2-oauth2-server#144]
See file <project_root>\vendor\bshaffer\oauth2-server-php\src\OAuth2\ResponseType\AuthorizationCode.php:60

There is an option to set the AuthorizationCode's lifetime in the dependance OAuth server from https://github.com/bshaffer/oauth2-server-php which this package uses, except this is not configurable through this Yii package. This might cause problems on slow networks when the request takes longer than 30 seconds (the current 'default').

**Comment by varp** [comment]
@NickvdMeij Please, correspond to the Configuration section of README.md, for guidance on how to set `auth_code_lifetime`.
