### ISSUE TITLE
Grant types and oauth_public_keys missing

### ISSUE THREAD

**Issue by tibee** [Filsh/yii2-oauth2-server#16]
Hello!

In file `Module.php` on line 39-42:

```php
 $server->addGrantType(new \OAuth2\GrantType\UserCredentials($storages['user_credentials']));
 $server->addGrantType(new \OAuth2\GrantType\RefreshToken($storages['refresh_token'], [
        'always_issue_new_refresh_token' => true
]));
```

Only these 2 grant types are added to server. Without overriding this class, I cannot add other grant types that are already supported by `bshaffer/oauth2-server-php`.

- Why is it neccessary to wire these 2 grant types into this file, as the default ones would be sufficient of `bshaffer/oauth2-server-php`, and these could be restricted in table `oauth_clients`.
- In your migration there is a sample row in `oauth_clients` table, having grant type `client_credentials` set, but because of the aboves, it does not work...

```bash
curl -v -X POST -u testclient:testpass "http://api.test.domain/oauth2/token" -d 'grant_type=client_credentials'

{"name":"Bad Request","message":"Grant type \"client_credentials\" not supported","code":0,"status":400,"type":"yii\\web\\HttpException"}
```

- Why is the table `oauth_public_keys` missing from your migration?

```sql
CREATE TABLE oauth_public_keys (
client_id VARCHAR(80),
public_key VARCHAR(2000),
private_key VARCHAR(2000),
encryption_algorithm VARCHAR(100) DEFAULT "RS256"
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Thank you!

**Comment by Filsh** [comment]
H, done :)
See commit https://github.com/Filsh/yii2-oauth2-server/commit/7a1176b8db54be89526dbefd8f075c4062e97c63

For example config

 ```php
 'oauth2' => [
     'class' => 'filsh\yii2\oauth2server\Module',
     'options' => [
         'token_param_name' => 'accessToken',
         'access_lifetime' => 3600
     ],
     'storageMap' => [
         'user_credentials' => 'common\models\User'
     ],
     'grantTypes' => [
         'client_credentials' => [
             'class' => '\OAuth2\GrantType\ClientCredentials',
             'allow_public_clients' => false
         ],
         'user_credentials' => [
             'class' => '\OAuth2\GrantType\UserCredentials'
         ],
         'refresh_token' => [
             'class' => '\OAuth2\GrantType\RefreshToken',
             'always_issue_new_refresh_token' => true
         ]
     ],
 ]
 ```

**Comment by tibee** [comment]
Hello, thank you!

What about the `oauth_public_keys` table?

**Comment by Filsh** [comment]
Also added in commit https://github.com/Filsh/yii2-oauth2-server/commit/7a1176b8db54be89526dbefd8f075c4062e97c63

**Comment by mtangoo** [comment]
#43
