### ISSUE TITLE
Add support for option refresh_token_lifetime

### ISSUE THREAD

**Issue by frock81** [Filsh/yii2-oauth2-server#17]
Could you add support for the *refresh_token_lifetime* option for the Refresh Token grant type?

I thought something like:

```php
class Module extends \yii\base\Module
{
    // ...
    
    public $refreshTokenLifetime = 2419200;

    // ...

    public function getServer($force = false)
    {
        // ...
            $server->addGrantType(new \OAuth2\GrantType\RefreshToken($storages['refresh_token'], [
				'always_issue_new_refresh_token' => true,
				'refresh_token_lifetime' => $this->refreshTokenLifetime,
            ]));
            
            // ...
```

And could be configured in the config file:

```php
'oauth2' => [
			'class' => 'filsh\yii2\oauth2server\Module',
			'options' => [
				'token_param_name' => 'access_token',
				'access_lifetime' => 3600 * 24,
				'allow_implicit' => true,
				'enforce_state' => false,
				'enforce_redirect' => true,
			],
			'storageMap' => [
				'user_credentials' => 'api\modules\v1\models\User'
			],
			'refreshTokenLifetime' => 2419200,
		],
```

**Comment by Filsh** [comment]
Hi, I have added options for storage configuration, see this commit https://github.com/Filsh/yii2-oauth2-server/commit/808918414efb17325308c90aaaf666096a102ec6

For example
```php
'oauth2' => [
      'class' => 'filsh\yii2\oauth2server\Module',
      'storageOptions' => [
          'refresh_token' => [
              'always_issue_new_refresh_token' => true
          ]
      ]
  ]
```

But option 'refresh_token_lifetime' must be used in 'options' section
```php
'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'options' => [
                ...
                'refresh_token_lifetime' => 2419200,
                ...
            ]
        ],
```

See more https://github.com/bshaffer/oauth2-server-php/search?q=refresh_token_lifetime

**Comment by Filsh** [comment]
Updated issue https://github.com/Filsh/yii2-oauth2-server/issues/16

**Comment by frock81** [comment]
Thank you for your attention and I'm sorry. Didn't know that.

**Comment by russ666** [comment]
now there are no way to specify refresh_token_lifetime

**Comment by Filsh** [comment]
Hi, added option in this commit https://github.com/Filsh/yii2-oauth2-server/commit/276b1058279972bdc4d4126084ca7c061d1087d3

**Comment by russ666** [comment]
Thank you!

**Comment by mtangoo** [comment]
#43

**Comment by jaminm** [comment]
The latest build does not have this option any more. Is there a reason it was removed?
