### ISSUE TITLE
Error when using tablePrefix

### ISSUE THREAD

**Issue by manoelt** [Filsh/yii2-oauth2-server#20]
Filsh,

When using tablePrefix, migrations creates all tables correctly, but the Pdo.php is not overwriting the $config variable from OAuth2\Storage\Pdo.php.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.oauth_access_tokens' doesn't exist

Thanks for your work.

**Comment by Filsh** [comment]
fixed, https://github.com/Filsh/yii2-oauth2-server/commit/0c05c5baa3ac8f67ea885490b5981a938a13352f

**Comment by manoelt** [comment]
Thank you.
