### ISSUE TITLE
Customize oauth2/token method

### ISSUE THREAD

**Issue by dungphanxuan** [Filsh/yii2-oauth2-server#28]
Hello, now i want to customize oauth2/token method, so can i do. I want to show more information with response message. thanks

**Comment by Filsh** [comment]
hi, your should rewrite controller action and use server
```php
$response = Yii::$app->getModule('oauth2')->getServer()->handleTokenRequest();
var_dump($response);
```

**Comment by mtangoo** [comment]
#43
