### ISSUE TITLE
filsh\yii2\oauth2server\storage\Pdo

### ISSUE THREAD

**Issue by wgwcyroot** [Filsh/yii2-oauth2-server#31]
filsh\yii2\oauth2server\Module

public function getServer($force = false, $config=array())
    {
        if($this->_server === null || $force === true) {
            $storages = [];
            foreach($this->storageMap as $name => $value) {
                $storages[$name] = \Yii::$container->get($name, array(),$config);
            }
            $server = new \OAuth2\Server($storages, $this->options);
            
            foreach($this->grantTypes as $name => $options) {
                if(!isset($storages[$name]) || empty($options['class'])) {
                    throw new \yii\base\InvalidConfigException('Invalid grant types configuration.');
                }
                
                $class = $options['class'];
                unset($options['class']);
                
                $reflection = new \ReflectionClass($class);
                $config = array_merge([0 => $storages[$name]], [$options]);

                $instance = $reflection->newInstanceArgs($config);
                $server->addGrantType($instance);
            }
            
            $this->_server = $server;
        }
        return $this->_server;
    }

this config can merge OAuth2\Storage\Pdo class config property 

$this->config = array_merge(array(
            'client_table' => 'oauth_clients',
            'access_token_table' => 'oauth_access_tokens',
            'refresh_token_table' => 'oauth_refresh_tokens',
            'code_table' => 'oauth_authorization_codes',
            'user_table' => 'oauth_users',
            'jwt_table'  => 'auth_jwt',
            'scope_table'  => 'oauth_scopes',
            'public_key_table'  => 'oauth_public_keys',
        ), $config);

because my database table has prefix cp_

**Comment by shcherbanich** [comment]
https://github.com/Filsh/yii2-oauth2-server/pull/35

**Comment by Filsh** [comment]
Updated in https://github.com/Filsh/yii2-oauth2-server/commit/0c05c5baa3ac8f67ea885490b5981a938a13352f
