### ISSUE TITLE
upgrading from 1 to 2 problems

### ISSUE THREAD

**Issue by draganescu** [Filsh/yii2-oauth2-server#32]
Hi,

Simply putting v2 in composer broke our app with this:

Setting unknown property: filsh\yii2\oauth2server\Module::options

Any clue?

**Comment by aotd1** [comment]
Replace in config:
```php
            'options' => [
                'token_param_name' => 'accessToken',
                'access_lifetime' => 3600 * 24
            ],
```

with
```php
            'tokenParamName' => 'accessToken',
            'tokenAccessLifetime' => 3600 * 24,
```

**Comment by hoodlumer** [comment]
Hi,

I am posting this via postman 

POST http://localhost:8085/oauth2/token

    {"grant_type":"password","username":"admin@api.loc","password":"123","client_id":"testclient","client_secret":"testpass"}

and get following exception

Unknown Property – yii\\base\\UnknownPropertyException

Setting unknown property: filsh\\yii2\\oauth2server\\Module::tokenParamName

1. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Component.php\n \n at line 197
$behavior->$name = $value;\n \n                    return;\n                }           }       }       if (method_exists($this, 'get' . $name)) {           throw new InvalidCallException('Setting read-only property: ' . get_class($this) . '::' . $name);\n        } else {           throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);   }

2. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\BaseYii.php\n \n at line 518
yii\\base\\Component::__set('tokenParamName', 'accessToken') 

3. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Object.php\n \n at line 105 yii\\BaseYii::configure(filsh\\yii2\\oauth2server\\Module, ['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]]) 

4. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Module.php\n \n at line 138 yii\\base\\Object::__construct(['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]]) 

5. yii\\base\\Module::__construct('oauth2', yii\\web\\Application, ['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]]) 

6. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\di\\Container.php\n \n at line 372 ReflectionClass::newInstanceArgs(['oauth2', yii\\web\\Application, ['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]]])
 
7. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\di\\Container.php\n \n at line 151
yii\\di\\Container::build('filsh\\yii2\\oauth2server\\Module', ['oauth2', yii\\web\\Application], ['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]])

8. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\BaseYii.php\n \n at line 344
 yii\\di\\Container::get('filsh\\yii2\\oauth2server\\Module', ['oauth2', yii\\web\\Application], ['tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], 'grantTypes' => ['user_credentials' => ['class' => 'OAuth2\\GrantType\\UserCredentials'], 'refresh_token' => ['class' => 'OAuth2\\GrantType\\RefreshToken', 'always_issue_new_refresh_token' => true]]])

9. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Module.php\n \n at line 354
yii\\BaseYii::createObject(['class' => 'filsh\\yii2\\oauth2server\\Module', 'tokenParamName' => 'accessToken', 'tokenAccessLifetime' => 86400, 'storageMap' => ['user_credentials' => 'api\\models\\User'], ...], ['oauth2', yii\\web\\Application])

10. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Module.php\n \n at line 511 yii\\base\\Module::getModule('oauth2')

11. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\base\\Module.php\n \n at line 449 yii\\base\\Module::createController('oauth2/default/token')

12. in C:\\Data\\yii\\yii2-advanced-api\\vendor\\yiisoft\\yii2\\web\\Application.php\n \n at line 84 yii\\base\\Module::runAction('oauth2/default/token', []) 


config module is set up as follows :

        'oauth2' => [
		    'class' => 'filsh\yii2\oauth2server\Module',
		    'tokenParamName' => 'accessToken',
		    'tokenAccessLifetime' => 3600 * 24,
		    'storageMap' => [
		        'user_credentials' => 'api\models\User',
		    ]

Any pointers?
Thanks

**Comment by hoodlumer** [comment]
Did a composer update to get yii2-oauth2-server 2.0.0 and bshaffer/oauth2-server-php ~1.7.1. I still had to get latest Module.php, Server.php, Request.php & Response.php files as these were not included in the update. This solved the problem

**Comment by mtangoo** [comment]
#43
