### ISSUE TITLE
Problems with v2.0.1

### ISSUE THREAD

**Issue by hiqsol** [filsh/yii2-oauth2-server#39]
**1.** Is v2.0.1 release supposed to be used? I failed to make it working :( While master branch version works just fine.

**2.** I don't get the idea of removing $options from Module and substition it with tokenParamName and others and then converting it back with:

``` php
    [
        'token_param_name' => $this->tokenParamName,
        'access_lifetime' => $this->tokenAccessLifetime,
        'refresh_token_lifetime' => $this->tokenRefreshLifetime,
        /** add more ... */
    ],  
```

I've counted - there are 34 config options in bshaffer/oauth2-server-php
Are you going to add them all?And keep in sync with bshaffer all the time?
Isn't your package supposed to be a thin wrapper?

For example I use 'enforce_state' option, I could add it to Module.php. But then it needs Pull Request
and all the procedure to get working. While $options just works, and anybody can add
any of currently available 34 options and any added in future.

**3.** Storage map initialization doesn't work.
Now it is:

``` php
            foreach(array_keys($this->storageMap) as $name) {
                $storages[$name] = \Yii::$container->get($name);
            }
```

while the storageMap config is like this:

``` php
            'storageMap' => [
                'user_credentials'  => 'common\models\User',
            ],
```

So it tries:

``` php
Yii::$container->get('user_credentials')
```

which ends with error:

```
Class user_credentials does not exist
```

Shouldn't initialization be like it was previously:

``` php
            foreach($this->storageMap as $name => $class) {
                $storages[$name] = \Yii::$container->get($class);
            }
```

It does make sense and seems working.

Thank in advance for any help :)

**Comment by Filsh** [comment]
Hi
2. Yes, it's a bad idea and should go back
3. I can not reproduce this error, the module is bootstrapped?

**Comment by hiqsol** [comment]
**3.** Yes, I've missed bootstrapping.
But I'm pretty sure bootstrapping of oauth2 module should not be mandatory.
initModule() should be moved to init() instead of bootstrap(). (I tested it works fine)
bootstrap() is called on every invocation of the whole application so it slows down all the requests to application that don't use oauth2.

And this part of bootstrap() makes sense only for console application.
```php
          if ($app instanceof \yii\console\Application) {
              $this->controllerNamespace = 'filsh\yii2\oauth2server\commands';
          }
```
so
```php
'bootstrap' => ['oauth2'],
```
can be put only to console application configuration.

**Comment by edeis53** [comment]
I have the same error, re: Class user_credentials does not exist.

How exactly is the module suppose to be boot strapped? I didn't see that in the install readme.

**Comment by jose1824** [comment]
Don't use stable use dev in your composer:

 ```
"minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "filsh/yii2-oauth2-server": "~2.0"
    },
```

**Comment by edeis53** [comment]
I'm going to move my bug over to https://github.com/Filsh/yii2-oauth2-server/issues/84

**Comment by varp** [comment]
Fixed in the master branch and the latest release.
