### ISSUE TITLE
Proper Documentation...

### ISSUE THREAD

**Issue by JavaMachine** [Filsh/yii2-oauth2-server#42]
I have read every post... but couldn't find step-by-step tutorial or examples how to use this extension :( Dear fellow developers, is there anyone who have figured out?

Any help appreciated :)

p.s. the problem is "You are requesting with an invalid credential."
(the request url is "https://localhost/accounts/index?grant_type=password&username=test&password=test&client_id=testclient&client_secret=testpass")

I tried https://localhost/oauth2/token?grant_type=password&username=test&password=test&client_id=testclient&client_secret=testpass and it gave me 404 Error...

Yes I have included "'POST oauth2/<action:\w+>' => 'oauth2/default/<action>'," in my urlmanager...

**Comment by thejahweh** [comment]
I've finally managed it to work in "some" cases.

* Add the module config described.
* Add this URL rule `'oauth2/token' => 'oauth2/rest/token'`
* Setup a user model which implements `OAuth2\Storage\UserCredentialsInterface` and `IdentityInterface\yii\web`.

If you've done this steps you should be able to get an `access_token`.

**Comment by JavaMachine** [comment]
![image](https://cloud.githubusercontent.com/assets/5568121/9303021/b354664e-44f4-11e5-8b86-fa196905c0dd.png)

Thanks for your answer... but the problem is... it shows me above message which is ok... but when I try to auth with client id and client secret (no matter Correct or incorrect password) it returns 404 error... it seems controller is trying to redirect to somewhere...

p.s. I am confused with username and password where it all stored? in database or in User class? (I mean array of users such as admin admin)

**Comment by thejahweh** [comment]
Your first error just says whats wrong, you didn't sent it via POST.

The 404 may because you doesn't set up your routing or module properly. The route `oauth2/rest/token` should work if you set the oauth2 module to `oauth2` and you use the newest version (difference to the old version is `oauth2/default/token`.

You have to store the username/password by yourself, I've done it via `ActiveRecord`.

**Comment by JavaMachine** [comment]
Thank you one more time :) here is module config:
'modules' => [
        'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'tokenParamName' => 'accessToken',
            'tokenAccessLifetime' => 3600 * 24,
            'storageMap' => [
                'user_credentials' => 'app\models\User',
            ],
        ],
    ],

I am new to yii so where I should setup routing?
p.s. Can I ask you to do me a favour ?) Could you please share your way of implementation of Oauth2 (maybe small tutorial) ? if not, any hints that could help newbie programmer :) I am developing small JSON api, and I stucked with this... aand almost 1 week no development and improvements :(

Thanks in advance...

**Comment by JavaMachine** [comment]
@thejahweh I have read you last comment for the last 4 hours repeatedly) Now I got what you wanted to say)) Thank you one more time)))

**Comment by JavaMachine** [comment]
@thejahweh and the last problem is 
![image](https://cloud.githubusercontent.com/assets/5568121/9324251/f3e7777a-45a1-11e5-89ca-ae94d8341f01.png)

and I think this is because of:
![image](https://cloud.githubusercontent.com/assets/5568121/9324272/22bf6d3c-45a2-11e5-9fd1-ac368e3ddb9e.png)

**Comment by thejahweh** [comment]
Yep there should stay something like this:
```php
/**
 * @inheritdoc
 */
public function checkUserCredentials($username, $password)
{
	$user = static::findOne([
		'email' => $username,
	]);
	if ($user !== null) {
		return Yii::$app->getSecurity()->validatePassword($password, $user->password);
	}
	return false;
}
/**
 * @inheritdoc
 */
public function getUserDetails($username)
{
	$user = static::findOne(['username' => $username]);
	/* @var $user static */
	if ($user === null) {
		return false;
	}
	return [
		'user_id' => $user->id,
	];
}
```

**Comment by JavaMachine** [comment]
You are great man)) :)
and I need your help with last issue)

I have Accounts Controller which is configures as documentation says..
![image](https://cloud.githubusercontent.com/assets/5568121/9328393/b2d1179e-45c1-11e5-9c96-9fe57b8e4631.png)

And index page return List of accounts in JSON Format...
![image](https://cloud.githubusercontent.com/assets/5568121/9328399/c28f3cf6-45c1-11e5-9090-3c66bd1f395d.png)

and when I try to access page with access Token... 
(https://localhost/accounts/index?accessToken=aa991ffcd65b5f1c3ce7dbfc726f324ebdcfb22b)

it gives me error:
![image](https://cloud.githubusercontent.com/assets/5568121/9328557/0814ed60-45c3-11e5-87a1-dee6fb004e4b.png)

Where am I doing wrong? How should I pass access_token?

Thanks in advance....

**Comment by thejahweh** [comment]
You could use the `yii\rest\ActiveController` which would do the most things for you.

The problem that you have is related to #44. You have to send a bearer token like this:
![image](https://cloud.githubusercontent.com/assets/10514993/9334292/6687dd7a-45ce-11e5-9901-8c2ef4415b01.png)
It is not possible to do it with the access token param.

**Comment by JavaMachine** [comment]
Thank you for your help)

**Comment by mtangoo** [comment]
#43

**Comment by nadeemse** [comment]
Thanks man for saving me hour's of effort.

**Comment by mtangoo** [comment]
just related questions. Is there a way to send just username+password+clientid?
It seems like I have to send client secret too, each time I request a token. In JS app its not wise to expose secret key

Also how do I send refresh token to get new one?
