### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by laxity7** [filsh/yii2-oauth2-server#45]
When applying of migration there is an error

``` php
PHP Strict Warning 'yii\base\ErrorException' with message 'Declaration of m140501_075311_add_oauth2_server::primaryKey() should be compatible with yii\db\Migration::primaryKey($length = NULL)'
```

Need set Null on default in primaryKey function `public function primaryKey($columns = null)` or rename function

**Comment by nadeemse** [comment]
Thanks Man, 
$columns = null save my hour.

**Comment by ruslanbes** [comment]
Setting $columns = null worked for me too (Postgres 9.4). Pull Request maybe?
