### ISSUE TITLE
POST oauth2/token method to GET oauth2/token

### ISSUE THREAD

**Issue by JavaMachine** [Filsh/yii2-oauth2-server#49]
Hello fellow developers...
Is it possible to authorize via GET request (p.s. oauth2/token?grant_type=password&username=test&password=test&client_id=testclient&client_secret=testpass) ?

When I try to auth via GET it returns me:
{"name":"Method Not Allowed","message":"The request method must be POST when requesting an access token","code":0,"status":405,"type":"filsh\\yii2\\oauth2server\\exceptions\\HttpException"}

I am facing problems with implementing client-side... It seems most of the ready libraries for android supports authorization via GET request...

Thanks in advance :)

**Comment by JavaMachine** [comment]
UP! :(

**Comment by Patroklo** [comment]
I think hat you'll have to change the library itself, not the Filsh one, but the server in which it's based. Can't recommend that.

**Comment by JavaMachine** [comment]
@Patroklo :) thank you for your answer) I had to implement my own OAuth2 client)

**Comment by mtangoo** [comment]
Why?

**Comment by JavaMachine** [comment]
@mtangoo Why? what?)

**Comment by mtangoo** [comment]
> I had to implement my own OAuth2 client)

**Comment by JavaMachine** [comment]
As I said in my main post:

"I am facing problems with implementing client-side... It seems most of the ready libraries for android supports authorization via GET request..."

**Comment by mtangoo** [comment]
You said 
>Is it possible to authorize via GET request (p.s. oauth2/token?grant_type=password&username=test&password=test&client_id=testclient&client_secret=testpass) ? 
Then down the lane
>I am facing problems with implementing client-side... It seems most of the ready libraries for android supports authorization via GET request...

As I undestood, you wanted to authorize with GET and Android libraries supports it already. So why did you have to write your own?

**Comment by Patroklo** [comment]
It seems that the problem is that client or resource granting don't allow get callings.

**Comment by mtangoo** [comment]
His/Her post is a bit vague as to what is exactly the problem and what's solution. I asked because if someone hits the post in search of solution it will not be helpful!

**Comment by Patroklo** [comment]
As I understand: @JavaMachine  it's using an OAuth client that has downloaded somewhere(probably GitHub) that only uses GET callings to the OAuth servers sending the login configuration. That's not standarised at all, but well... And his problem it's that he want to use this module with GET method and the Token granting system only accept POST methods.

**Comment by JavaMachine** [comment]
@Patroklo Yeah) that's right... the problem was that I could not find ready library for OAuth2 Client :( and yes... I downloaded it somewhere on GitHub :(

@mtangoo Android supports GET and Yii OAuth2 Extension not supports it :(

**Comment by mtangoo** [comment]
@JavaMachine  I see.
