### ISSUE TITLE
Controller Token Behavior

### ISSUE THREAD

**Issue by Patroklo** [filsh/yii2-oauth2-server#51]
After studiying the @mtangoo library based in this module and the specification in the documentation of this module, I have a question about the use of  CompositeAuth::className() as an authenticator. 

It's supposed to be able to stop a query without token, but it only checks that in the beforeAction step. Also it doesn't throw an error or anything. It only checks if token is valid and if it is or isn't, continues the check calling in the example two authmethods that check the access token in the declared component user model that maybe or maybe not have a valid loginByAccessToken call with the oauth token. (code comes a little confusing here, sorry). Shouldn't be better to implement a more direct approach compatible with oauth authentication based ONLY in token checking and, if we want to add something more (which in theory would be breaking the oauth2 standard) have an option for that?

**Comment by mtangoo** [comment]
Can you post how you use it? 
And, may I know which of my library are you referring to?

**Comment by Patroklo** [comment]
Code is as stated in the readme here: 

   return ArrayHelper::merge(parent::behaviors(), [
            'authenticator' => [
                'class' => CompositeAuth::className(),
                'authMethods' => [
                    ['class' => HttpBearerAuth::className()],
                    ['class' => QueryParamAuth::className(), 'tokenParam' => 'accessToken'],
                ]
            ],
            'exceptionFilter' => [
                'class' => ErrorToExceptionFilter::className()
            ],
        ]);

Problem is that I am using [amnah](https://github.com/amnah/yii2-user) user system, so the call to findIdentityByAccessToken is not valid. In my opinion the library should check the token and let us handle the user check in.

About the library, I was wrong, its from @ikaras https://github.com/ikaras/yii2-oauth2-rest-template

**Comment by subangkit** [comment]
Integration between Filsh OAuth2 and Amnah User you need to changin 2 files. 
1. Change your OAuth2 user storage in main.php
```php
'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'tokenParamName' => 'accessToken',
            'tokenAccessLifetime' => 3600 * 24,
            'storageMap' => [
                'user_credentials' => 'amnah\yii2\user\models\User',
            ],
            'grantTypes' => [
                'user_credentials' => [
                    'class' => 'OAuth2\GrantType\UserCredentials',
                ],
                'refresh_token' => [
                    'class' => 'OAuth2\GrantType\RefreshToken',
                    'always_issue_new_refresh_token' => true
                ]
            ]
        ],
```
2. Change models User.php in amnah vendor
```php
public static function findIdentityByAccessToken($token, $type = null)
    {
        $storage = new \filsh\yii2\oauth2server\storage\Pdo(null,array());
        $accessToken = $storage->getAccessToken($token);
        if (($accessToken['expires'] - time()) > 0) {
            $user_id = $accessToken['user_id'];
            return static::findOne($user_id);
        }
        return static::findOne(["api_key" => $token]);
    }
```
3. Add Code for OAuth2 Integration in Amnah
```php
/**
     * @inheritdoc
     */
    public function getUserDetails($username)
    {
        $user = static::findOne(['username' => $username]);
        /* @var $user static */
        if ($user === null) {
            return false;
        }
        return [
            'user_id' => $user->id,
        ];
    }

    public function loginByAccessToken($token, $type = null)
    {
        /* @var $class IdentityInterface */
        $class = $this->identityClass;
        $identity = $class::findIdentityByAccessToken($token, $type);
        if ($identity && $this->login($identity)) {
            return $identity;
        } else {
            return null;
        }
    }
```
4. And Access with your_url?accessToken=Blablabla
5. Thankyou

**Comment by mtangoo** [comment]
:+1:
