### ISSUE TITLE
Setting unknown property: filsh\yii2\oauth2server\Module::options

### ISSUE THREAD

**Issue by vishnupriyam** [Filsh/yii2-oauth2-server#60]
After updating yo yii2.0.6 - when I run my application - I get the following error:

    Setting unknown property: filsh\yii2\oauth2server\Module::options

The issue is due the 

    'options' =>[
        'token_param_name' => 'access_token',
        'access_lifetime' => 3600 * 24
    ]

setting in the application/config/common.php under the oauth2 module which was done according to README.md

**Comment by vishnupriyam** [comment]
Please update readme.md that settings have to be done in following manner:

    'tokenParamName' => 'accessToken',
    'tokenAccessLifetime' => 3600 * 24,

**Comment by mtangoo** [comment]
@vishnupriyam make a [PR](https://help.github.com/articles/creating-a-pull-request/)

**Comment by vishnupriyam** [comment]
made one already  : https://github.com/Filsh/yii2-oauth2-server/pull/61
