### ISSUE TITLE
Class 'filsh\yii2\oauth2server\Request' not found

### ISSUE THREAD

**Issue by wdzulc** [filsh/yii2-oauth2-server#71]

**Comment by wdzulc** [comment]
when i try to edit Module.php using: 

use OAuth\Request;

This issue is repaired but throw: 

exception 'ReflectionException' with message 'Class user_credentials does not exist'

**Comment by manoelt** [comment]
Same problem as described here: https://github.com/Filsh/yii2-oauth2-server/issues/68

@mtangoo @Filsh

**Comment by mtangoo** [comment]
As I said earlier somewhere in comments,master branch is quiet a different beast and to my surprise its not the most updated as one would expect. So I suggest you change your composer from dev-master to 2.0.1 branches. That will give you the latest version that is working. @Filsh will have to revert the merg of my two PR in master branch for it to work. IMHO 2.0.1 is actually the "master" branch

**Comment by viyancs** [comment]
i have same problem on Centos with apache2 no  issue, but when migration in ubuntu apache2 have this issue.

**Comment by mtangoo** [comment]
Please check the readme in **2.0.1 BRANCH ** then install that one.
