### ISSUE TITLE
function findIdentityByAccessToken

### ISSUE THREAD

**Issue by vzani** [Filsh/yii2-oauth2-server#76]
Hello,

I have a question about the following function:

```
public static function findIdentityByAccessToken($token, $type = null)
    {
        /** @var \filsh\yii2\oauth2server\Module $module */
        $module = Yii::$app->getModule('oauth2');
        $token = $module->getServer()->getResourceController()->getToken();
        return !empty($token['user_id'])
                    ? static::findIdentity($token['user_id'])
                    : null;
    }

```

What´s the point of sending $token by parameter if it´s overwritten on that line, before using it?

`$token = $module->getServer()->getResourceController()->getToken();`

**Comment by mtangoo** [comment]
Its a requirement by [the interface](http://www.yiiframework.com/doc-2.0/yii-web-identityinterface.html#findIdentityByAccessToken%28%29-detail)
Personally I have not tested what is passed to that method. Can you check if `$token` passed and the one got from `$module->getServer()->getResourceController()->getToken();` are the same?

**Comment by vzani** [comment]
I just made a test:

Token From Parameter: 0a1f313bfb09b329826c6fc60b993078b460c347 
Token Module (an array):
Array ( [access_token] => 0a1f313bfb09b329826c6fc60b993078b460c347 [client_id] => webclient [user_id] => 54 [expires] => 1488115552 [scope] => ) 

So yes, they are the same. Looking at the function its weird and I didnt think about the interface signature.

Thanks
