### ISSUE TITLE
add revoke request

### ISSUE THREAD

**Issue by lisps** [filsh/yii2-oauth2-server#80]
can you add accessToken and refreshToken revokes?

**Comment by mtangoo** [comment]
Is that functionality available [original module?](https://github.com/bshaffer/oauth2-server-php)

**Comment by lisps** [comment]
in https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Controller/TokenController.php there is a method handleRevokeRequest. 
So I think yes.

**Comment by mtangoo** [comment]
Can you fix and do a PR?
