### ISSUE TITLE
authenticate base on client token

### ISSUE THREAD

**Issue by jessicaoy** [filsh/yii2-oauth2-server#89]
just example, my API has got Resources and these have got some endpoints.

Resources:

frogs
API features:

frogs   readAll http://myapi.com/api/www/index.php/oauth2/v1/get/frogs
frogs   readOne GET http://myapi.com/api/www/index.php/oauth2/v1/get/frogs/{id} 
frogs   createOne   POST    http://myapi.com/api/www/index.php/oauth2/v1/frogs  (user credent only)
...

For authentification I use the yii2-oauth2-server and the grant_type "client credentials".
note : no problem with user credential auth. 
but i need just use authenticate base on client token, and always failed, how this scenario can be done?
1. Request:
   GET http://myapi.com/api/www/index.php/oauth2/token
   grand_type = client_credentials
   client_id = id1
   client_secret = secret1
2. Response:
   "access_token": "thisisthefunnyaccesstoken",
   "expires_in": 31104000,
   "token_type": "Bearer",
   "scope": "default"
3. Request:
   GET http://myapi.com/api/www/index.php/oauth2/v1/get/frogs
   HEADER Authorization: Bearer thisisthefunnyaccesstoken
4. Response:
   all the funny frogs

**Comment by jessicaoy** [comment]
now i can use client token using $_pos:

in controller :
if (isset($_post['token'])) token = $_post('token');

if ((Accesstokens::isAccessTokenValid($token))) {// do some thing.}

in my Accesstokens model :
public static function isAccessTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }
        $query = (new \yii\db\Query())
            ->select(['access_token','expires'])
            ->from('oauth_access_tokens')
            ->where(['access_token' => $token])
//            ->limit(10)
            ->one();
        if (empty($query)) {
            return false;
        }
        $expire = $query['expires'];
        return $expire > date('Y-m-d h:i:s');
    } 

how to use: HEADER Authorization: Bearer? anyone can help?

**Comment by jessicaoy** [comment]
if i use password (user_credential) token, i can implementation bearer auth using :

```
public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticator' => [
                'class' => CompositeAuth::className(),
                'authMethods' => [
                    ['class' => HttpBearerAuth::className()],
                    ['class' => QueryParamAuth::className(), 'tokenParam' => 'accessToken'],
                ]
            ],
            'exceptionFilter' => [
                'class' => ErrorToExceptionFilter::className()
            ],
        ]);
    }
```

but this method is using user table in authenticate user, not oauth_client table to authenticate client without user

how to authenticate token base on client table only, without user table?

**Comment by biessek** [comment]
if I understand, you want the client to have access without a user.
Looking at the table oauth_client has a user_id column. 

So, i believe that you must link the oauth_client to a user in your user table.

ie **for a oauth_client you must have a user to make this type of authentication**

for example, i use this in a migration to insert a basic api client:

``` 
        // create the oauth_client associated user.
            $user = new \api\models\User([
                     'name' => 'api_client_1',
                     'email' => 'api_client_1@email.com',
                     'password' => '', // I do not think I need it
                     'status' => 10]);
            $user->save();
```

```      
       // create the oauth_client itself:
        $oauth2Client = new \filsh\yii2\oauth2server\models\OauthClients([
            'client_id' => 'api_client_id_1',
            'client_secret' => 'api_client_secret', 
            'redirect_uri' => 'http://fake.com',
            'grant_types' => 'password client_credentials',
            'scope' => 'manipulate_users',
            'user_id' => \api\models\User::findOne(['name' => 'api_client_1'])->id,
        ]);
        $oauth2Client->save();
```
**Note:** **I do not know if this is the best way, i found nothing related in the documentation, but it is the way we use and it works.**


About using the token via header that is how you described it.
It would be the same as the user. Using `behaviors`.
That is, the only thing is to connect the oauth_client to the user.

**Comment by sno0p1** [comment]
@biessek Thanks, your solution work perfect.
yes about the token, just using behaviors.

**Comment by jonmunm** [comment]
Why the client_credentials grant_type must be provided with user credentials (in this implementation). The oauth2 client_credentials spec just needs 

```
{
    "grant_type" : "client_credentials",
    "client_id" : "some_id",
    "client_secret" : "some_secret"
}
```
