### ISSUE TITLE
How to pass a refresh_token_lifetime? (v. 2.0.1)

### ISSUE THREAD

**Issue by dimmitri** [filsh/yii2-oauth2-server#94]
Issues closed:
https://github.com/Filsh/yii2-oauth2-server/issues/17
https://github.com/Filsh/yii2-oauth2-server/issues/90
These solutions don't work.

**Comment by trueangle** [comment]
same issue

**Comment by dimidrol88** [comment]
same problem

**Comment by dev3k** [comment]
incase anyone still need this , check #37
