### ISSUE TITLE
Error applying migrations

### ISSUE THREAD

**Issue by memclutter** [filsh/yii2-oauth2-server#99]
This error appears when you start migration:

```
PHP Warning 'yii\base\ErrorException' with message 'Declaration of m140501_075311_add_oauth2_server::primaryKey($columns) should be compatible with yii\db\Migration::primaryKey($length = NULL)'
```

**Comment by cpmoser** [comment]
Easy to fix, just change the primaryKey method in the migration in m140501_075311_add_oauth2_server.php to add the default value:

```php
public function primaryKey($columns = null)
```

I guess they added the default value to the Migration class at some point?  Anyway, this should probably be fixed in the repo.

**Comment by cmoser4m** [comment]
Note: looks like it's already been fixed in master, probably just not in the version that's on packagist.
